# Generated by Django 4.2.5 on 2023-10-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.CharField(max_length=50, verbose_name='Верификация'),
        ),
    ]
