# Generated by Django 4.2.5 on 2023-10-03 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта клиента')),
                ('full_name', models.CharField(max_length=128, verbose_name='имя клиента')),
                ('comment', models.CharField(blank=True, max_length=512, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='дата и время начала рассылки')),
                ('end_time', models.DateTimeField(verbose_name='дата и время окончания рассылки')),
                ('interval', models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=10, verbose_name='интервал')),
                ('status', models.CharField(default='created', max_length=10, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'настройка рассылки',
                'verbose_name_plural': 'настройки рассылок',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, verbose_name='тема письма')),
                ('body', models.CharField(max_length=1024, verbose_name='тест письма')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter', verbose_name='сообщение для рассылки')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='дата в время попытки')),
                ('status', models.CharField(choices=[('success', 'успешно'), ('failure', 'ошибка')], max_length=7, verbose_name='статус')),
                ('response', models.TextField(blank=True, null=True, verbose_name='ответ')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.message')),
            ],
            options={
                'verbose_name': 'результат рассылки',
                'verbose_name_plural': 'результат рассылок',
            },
        ),
    ]
