# Generated by Django 4.2.5 on 2023-10-07 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_remove_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='start_time',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время начала рассылки'),
        ),
    ]
