# Generated by Django 4.2.5 on 2023-10-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_newsletter_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='newsletter.message'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='recipients',
            field=models.ManyToManyField(related_name='newsletters', to='newsletter.client'),
        ),
    ]
