# Generated by Django 4.2.5 on 2023-10-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_message_newsletter_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержимое статьи')),
                ('image', models.ImageField(null=True, upload_to='blog_images/', verbose_name='изображение')),
                ('views', models.IntegerField(default=0, null=True, verbose_name='количество просмотров')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'пост блога',
                'verbose_name_plural': 'посты блога',
            },
        ),
    ]
