# Generated by Django 4.2.5 on 2023-10-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_client_creator_message_creator_newsletter_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='recipients',
        ),
        migrations.AddField(
            model_name='log',
            name='client',
            field=models.EmailField(max_length=150, null=True, verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='log',
            name='newsletter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter', verbose_name='рассылка'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='Client',
            field=models.ManyToManyField(to='newsletter.client', verbose_name='получатель'),
        ),
        migrations.AlterField(
            model_name='log',
            name='response',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('success', 'успешно'), ('failure', 'ошибка')], default='Успешно', max_length=50, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.message', verbose_name='сообщение'),
        ),
    ]
